version: 2.1

orbs:
  eb: circleci/aws-elastic-beanstalk@1.0.0
  node: circleci/node@4.1.0

workflows:
  elastic-beanstalk-workflow:
    jobs:
      - run:
          name: Install Node Packages.
          command: npm i
      - eb/deploy:
          context: aws-creds
          environment-name: Circledev-env
          filters:
            branches:
              only:
                - main
          